<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1T5BJDV" failures="2" tests="5" name="Authorization" time="4.367" errors="0" timestamp="2024-07-09T19:47:46 IST">
  <testcase classname="authentication.Login" name="tC_01test_passed" time="2.505"/>
  <testcase classname="authentication.Login" name="tC_02test_Failed" time="0.133">
    <failure type="java.lang.AssertionError" message="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: java.lang.AssertionError
at baseClases.Helper.triggerAssertFail(Helper.java:112)
at authentication.Login.tC_02test_Failed(Login.java:60)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.AssertionError
at authentication.Login.tC_02test_Failed(Login.java:55)
... 26 more
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- tC_02test_Failed -->
  <testcase classname="authentication.Login" name="tC_03test_Failed1" time="0.304">
    <failure type="java.lang.Exception" message="java.lang.Exception">
      <![CDATA[java.lang.Exception: java.lang.Exception
at baseClases.Helper.triggerExceptionFail(Helper.java:131)
at authentication.Login.tC_03test_Failed1(Login.java:72)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.Exception
at authentication.Login.tC_03test_Failed1(Login.java:70)
... 26 more
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- tC_03test_Failed1 -->
  <testcase classname="authentication.Login" name="tC_04test_Skip" time="0.003"/>
  <testcase classname="authentication.Login" name="tc_05PomTest" time="1.313"/>
</testsuite> <!-- Authorization -->
